services:
  gateway:
    build: .
    network_mode: "host"  # Use host networking to access localhost services
    environment:
      - PORT=8082
      - SEED_SECRET_KEY=${SEED_SECRET_KEY}
      - ALLOWED_TARGET_ORIGINS=localhost:8080,127.0.0.1:8080
      - TARGET_REWRITES={"localhost:8080":{"Scheme":"http","Host":"localhost:8080"},"localhost:9787":{"Scheme":"http","Host":"localhost:9787"},"localhost:9788":{"Scheme":"http","Host":"localhost:9788"}}
      - LOG_LEVEL=debug
      - LOG_FORMAT=json